# Generated by Django 5.1 on 2024-10-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='h_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media', verbose_name='page logo')),
                ('name', models.CharField(max_length=20, verbose_name='page name')),
                ('bgimg', models.ImageField(upload_to='media', verbose_name='img')),
                ('tel', models.CharField(max_length=20, verbose_name='tel')),
                ('email', models.CharField(max_length=70, verbose_name='email')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='h_what_do_we_have',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='number')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
