# Generated by Django 5.1 on 2024-10-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_h_header_h_what_do_we_have_delete_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_header',
            name='have_text',
            field=models.TextField(default=' ', verbose_name='text'),
        ),
    ]
