# Generated by Django 5.1 on 2024-10-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
