# Generated by Django 5.1 on 2024-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing', models.ImageField(upload_to='media', verbose_name='img')),
                ('date', models.DateField(verbose_name='date')),
                ('p', models.CharField(max_length=35, verbose_name='paragraf')),
                ('text', models.TextField(verbose_name='')),
            ],
        ),
    ]
