# Generated by Django 5.1 on 2024-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
                ('name', models.CharField(max_length=20, verbose_name='students name')),
                ('about', models.TextField(verbose_name='')),
            ],
        ),
    ]
