# Generated by Django 5.1 on 2024-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='name',
            field=models.CharField(default='img', max_length=20, verbose_name='img name'),
        ),
        migrations.AlterField(
            model_name='h_header',
            name='have_text',
            field=models.TextField(default=' ', verbose_name='1 havet text'),
        ),
    ]
