# Generated by Django 5.1 on 2024-10-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_callback_name_alter_h_header_have_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallBack',
            new_name='footer',
        ),
    ]
