# Generated by Django 5.1 on 2024-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='img', max_length=20, verbose_name='img name')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
                ('facebook', models.CharField(max_length=100, verbose_name='facebook link')),
                ('instagram', models.CharField(max_length=100, verbose_name='instagram link')),
                ('youtube', models.CharField(max_length=100, verbose_name='youtube link')),
            ],
        ),
    ]
